package uk.ac.qmul.sbcs.evolution.convergence;

public enum PhylogenyConvergenceType {
	REFERENCE_SPECIES_NULL_PHYLOGENY,
	TEST_ALTERNATIVE_PHYLOGENY,
	RANDOM_CONTROL_PHYLOGENY,
	RAXML_RESOLVED_PARTIALLY_CONSTRAINED_PHYLOGENY,
	RAXML_FULLY_RESOLVED_UNCONSTRAINED_PHYLOGENY
}
